language: java
sudo: false
script: cd com.googlecode.cppcheclipse.parent && mvn clean verify && cd .. 
script: ls -l com.googlecode.cppcheclipse.repository/target/*.zip
deploy:
  provider: bintray
  file_glob: true
  file: "com.googlecode.cppcheclipse.repository/target/com.googlecode.cppcheclipse*.zip"
  user: "$BINTRAY_USER"
  key: "$BINTRAY_API_KEY"
  