language: java
sudo: true
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y tree
script: cd com.googlecode.cppcheclipse.parent && mvn clean verify && cd .. && tree && ls -l ./com.googlecode.cppcheclipse.repository/target/*.zip
deploy:
  provider: bintray
  file: bintray-deploy.json
  user: "$BINTRAY_USER"
  key: "$BINTRAY_API_KEY"
  