language: java
sudo: false
script: cd com.googlecode.cppcheclipse.parent && mvn clean verify
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file_glob: true
  file: "com.googlecode.cppcheclipse.repository/target/com.googlecode.cppcheclipse*.zip"
  skip_cleanup: true
  on:
    tags: true
